import './globals.css'
import { ThemeProvider } from "@/components/theme-provider"
import { SiteHeader } from "@/components/site-header"
import { ConfiguratorProvider } from '@/contexts/Configurator'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ConfiguratorProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <SiteHeader />
              <div className="flex-1">{children}</div>
            </ThemeProvider>
          </ConfiguratorProvider>
        </body>
      </html>
    </>
  )
}