export const traits = {
  Type: [
    "Skeleton",
    "Purple",
    "Red",
    "Dark",
    "Orange",
    "Solana",
    "None",
    "Zombie",
    "Alien",
    "Brown",
  ],
  Hat: [
    "Black Backwards Cap",
    "White Fedora 2",
    "Black Cap",
    "None",
    "Horns",
  ],
  Eyes: [
    "VR Glasses",
    "Laser Eyes",
    "Cool Glasses",
    "Vipers",
    "None",
  ],
  Clothes: [
    "Beige Smoking",
    "Orange Kimono",
    "Orange Shirt",
    "Green Jacket",
    "None",
  ],
  Ears: [
    "Gold Earring",
    "Silver Earring",
    "None",
  ],
  Mouth: [
    "Vape",
    "Pipe",
    "Mask",
    "Cigarette",
    "None",
  ],
  Background: [
    "Blue",
    "Green",
    "Orange",
    "Purple",
    "Yellow",
    "Red",
    "None",
  ],
  "Attributes Count": ["1", "2", "3", "4", "5"],
} as const;